name: flutter_pos_printer_platform_image_3
description: A flutter plugin that prints esc commands to printers in different platforms such as android, ios, windows and different interfaces Bluetooth and BLE, TCP and USB
version: 1.2.4
homepage: https://github.com/diantahoc/flutter_pos_printer_platform

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  enum_to_string: ^2.0.1
  image_v3: ^3.3.0
  network_info_plus: ^4.0.2
  ping_discover_network_forked: ^0.0.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.sersoluciones.flutter_pos_printer_platform
        pluginClass: FlutterPosPrinterPlatformPlugin
      ios:
        pluginClass: FlutterPosPrinterPlatformPlugin
      windows:
        pluginClass: FlutterPosPrinterPlatformPlugin
